#!/usr/bin/env node
// AuditCore — génère le Banc de preuves depuis la fusion des packs + bindings des profils.
// Démonstration P5 : un livrable réel généré pour N tenants sans édition manuelle.
// Usage: node tools/build-banc.mjs <tenant.yaml> [--out <fichier.md>]
import fs from 'node:fs';
import path from 'node:path';
import { rel, loadTenant, loadJson, loadYaml, deriveBucket } from './lib.mjs';

const file = process.argv[2];
if (!file) { console.error('Usage: node tools/build-banc.mjs <tenant.yaml> [--out <fichier.md>]'); process.exit(2); }
const { cfg, tenantDir, resolveRef } = loadTenant(file);
const outIdx = process.argv.indexOf('--out');
const out = outIdx > -1 ? path.resolve(process.argv[outIdx + 1])
  : rel('deliverables', 'generated', cfg.tenant.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'), 'banc-de-preuves.md');

// fusion (mêmes règles que merge-packs, tolère les packs absents en construction)
const binding = cfg.enforcement?.binding_authorities ?? [];
const all = [];
for (const packRef of cfg.constraint_packs ?? []) {
  const p = resolveRef(packRef);
  if (!fs.existsSync(p)) continue;
  for (const c0 of loadJson(p).constraints ?? []) all.push({ ...c0, bucket: deriveBucket(c0, binding) });
}
// bindings des profils activés (control → instanciation)
const inst = new Map();
for (const prof of cfg.profiles ?? []) {
  const bp = rel('profiles', prof, 'bindings.json');
  if (!fs.existsSync(bp)) continue;
  for (const b of loadJson(bp).bindings ?? [])
    if (!inst.has(b.control)) inst.set(b.control, { profile: prof, ...b });
}
const lang = cfg.tenant?.language === 'en' ? 'en' : 'fr';
const dims = loadYaml(rel('core', 'dimensions', 'dimensions.yaml')).dimensions;
const dimLabel = Object.fromEntries(dims.map(d => [d.id, cfg.dimensions?.relabel?.[d.id] ?? (lang === 'en' ? (d.label_en ?? d.label) : d.label)]));
const B = lang === 'en'
  ? { titre: 'Evidence bench — audit actions by rule', gen: 'Generated by AuditCore', regles: 'merged rules', opp: 'binding', edit: 'Do not edit manually.',
      verdicts: 'Verdicts: compliant / partial / non-compliant (applicable, with evidence) · not applicable (justified) · to assess (specific reason required, keep rare)',
      rgl: 'rules', regle: 'Rule', actions: 'Audit actions', preuve: 'Expected evidence', grille: 'Verdict grid', stds: 'Standards', inst: 'Instantiation', verif: 'Verification' }
  : { titre: "Banc de preuves — actions d'audit par règle", gen: 'Généré par AuditCore', regles: 'règles fusionnées', opp: 'opposables', edit: 'Ne pas éditer à la main.',
      verdicts: 'Verdicts : conforme / partiel / non conforme (applicable, avec preuve) · sans objet (justifié) · à évaluer (motif obligatoire, à rendre rare)',
      rgl: 'règles', regle: 'Règle', actions: "Actions d'audit", preuve: 'Preuve attendue', grille: 'Grille de verdict', stds: 'Standards', inst: 'Instanciation', verif: 'Vérification' };

const byDim = new Map();
for (const c of all) {
  const d = (c.dimension_audit ?? '—').split(' · ')[0];
  if (!byDim.has(d)) byDim.set(d, []);
  byDim.get(d).push(c);
}
let md = `# ${cfg.tenant.name} — ${B.titre}\n\n> ${B.gen} (core ${cfg.core_version}) — ${all.length} ${B.regles} (${all.filter(c => c.bucket === 'opposable').length} ${B.opp}). ${B.edit}\n> ${B.verdicts}\n`;
for (const [d, items] of [...byDim.entries()].sort()) {
  md += `\n## ${d} — ${dimLabel[d] ?? ''} (${items.length} ${B.rgl})\n`;
  for (const c of items) {
    md += `\n### ${c.id} — ${c.criticite} · ${c.bucket} · enforcement \`${c.enforcement}\` · audit ${c.dimension_audit}\n`;
    md += `**${B.regle}** : ${c.regle}\n`;
    if (c.actions_audit?.length) md += `**${B.actions}** :\n${c.actions_audit.map(a => `- ${a}`).join('\n')}\n`;
    if (c.preuve_attendue) md += `**${B.preuve}** : ${c.preuve_attendue}\n`;
    if (c.grille_verdict) md += `**${B.grille}** : ${c.grille_verdict}\n`;
    if (c.standards?.length) md += `**${B.stds}** : ${c.standards.join(' · ')}\n`;
    const b = inst.get(c.id);
    if (b) md += `> ${B.inst} \`profil:${b.profile}\` — ${b.instanciation}\n> ${B.verif} : \`${b.verification_command}\`\n`;
  }
}
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, md, 'utf-8');
console.log(`✔ banc de preuves généré: ${all.length} règles, ${inst.size} instanciations profils → ${out}`);
