// AuditCore — moteur de rendu du rapport d'audit (M5 v1).
// Fonction PURE : (rapport-data, options) → HTML autonome thémé. Aucune E/S ici —
// consommée par build-rapport.mjs (repo) et inlinée dans les kits (standalone).
// v1 : bandeau gate + KPIs, radar par famille (SVG), onglets familles→dimensions
// (matrice de traçabilité, constats triés, plan d'action trié), onglet « Toutes les
// règles » filtrable, reprise applicative, impression. Hors v1 (v1.4) : ERD BDD,
// schéma d'architecture auto-layout.

const SEV = { critique: 0, majeur: 1, mineur: 2 };
const TAG = { urgent: 0, prio: 1, quick: 2, norm: 3 };
// i18n du moteur (RAF-012) — self-contained : les kits standalone inlinent ce fichier.
const STR = {
  fr: { rapport: "Rapport d'audit", gate: 'Verdict gate', score: 'Score global', instruites: 'dimensions instruites',
    bloquants: 'Bloquants', regles: 'Règles instruites', nc: 'non conformes', familles: 'Scores par famille',
    toutes: 'Toutes les règles', reprise: 'Reprise applicative', schemas: 'Architecture & BDD',
    regle: 'Règle', verdict: 'Verdict', preuve: 'Preuve / motif', remede: 'Remédiation', constats: 'Constats',
    plan: "Plan d'action", action: 'Action', effort: 'Effort', dim: 'Dim.', crit: 'Crit.', sans_regle: 'Aucune règle rattachée à cette dimension.',
    preuves_score: 'Preuves du score', so: 'sans objet', filtrer: 'Filtrer (id, verdict, texte)…', info: 'Information', valeur: 'Valeur', statut: 'Statut',
    erd: 'Schéma physique (ERD)', archi: 'Architecture logique', table: 'Table', colonnes: 'Colonnes', note: 'Note',
    legende_erd: '* = NOT NULL · [PK]/[UK]/[FK] = clés · 🔒 = donnée personnelle · trait plein = FK appliquée, pointillé = référence logique.',
    auditeur: 'auditeur', footer: "Rapport auto-portant · « pas de score sans preuve » · généré par AuditCore {v} pour {t} — vérifié par verifier-rapport (gate machine).",
    rem: 'Plan de remédiation', prio: 'Prio', source: 'Source', critere: 'Critère de clôture',
    rem_sans_critere: 'action(s) sans critère de clôture — rapport incomplet',
    rem_intro: "Plan exhaustif et auto-porté : actions des dimensions + règles non conformes. Extractible sans export manuel (verifier-remediation), et projeté en remediation-actions.yaml pour la forge.",
    tests: 'Tests', analyses: 'Analyses techniques', composants: 'Composants',
    type: 'Type', portee: 'Portée', resultat: 'Résultat', couverture: 'Couverture',
    outil: 'Outil', categorie: 'Catégorie', version_utilisee: 'Version utilisée',
    nom: 'Nom', version_resolue: 'Version résolue', version_actuelle: 'Version actuelle',
    reco: 'Reco', perimetre: 'Périmètre', moteur_llm: "Moteur d'audit (LLM)" },
  en: { rapport: 'Audit report', gate: 'Gate verdict', score: 'Overall score', instruites: 'dimensions assessed',
    bloquants: 'Blockers', regles: 'Rules assessed', nc: 'non-compliant', familles: 'Scores by family',
    toutes: 'All rules', reprise: 'Handover to operations', schemas: 'Architecture & DB',
    regle: 'Rule', verdict: 'Verdict', preuve: 'Evidence / reason', remede: 'Remediation', constats: 'Findings',
    plan: 'Action plan', action: 'Action', effort: 'Effort', dim: 'Dim.', crit: 'Crit.', sans_regle: 'No rule attached to this dimension.',
    preuves_score: 'Score evidence', so: 'not applicable', filtrer: 'Filter (id, verdict, text)…', info: 'Item', valeur: 'Value', statut: 'Status',
    erd: 'Physical schema (ERD)', archi: 'Logical architecture', table: 'Table', colonnes: 'Columns', note: 'Note',
    legende_erd: '* = NOT NULL · [PK]/[UK]/[FK] = keys · 🔒 = personal data · solid = enforced FK, dashed = logical reference.',
    auditeur: 'auditor', footer: 'Self-contained report · "no score without evidence" · generated by AuditCore {v} for {t} — checked by verifier-rapport (machine gate).',
    rem: 'Remediation plan', prio: 'Prio', source: 'Source', critere: 'Closure criterion',
    rem_sans_critere: 'action(s) without a closure criterion — incomplete report',
    rem_intro: 'Exhaustive, self-carried plan: dimension actions + non-compliant rules. Extractable without manual export (verifier-remediation), and projected to remediation-actions.yaml for the forge.',
    tests: 'Tests', analyses: 'Technical analyses', composants: 'Components',
    type: 'Type', portee: 'Scope', resultat: 'Result', couverture: 'Coverage',
    outil: 'Tool', categorie: 'Category', version_utilisee: 'Version used',
    nom: 'Name', version_resolue: 'Resolved version', version_actuelle: 'Current version',
    reco: 'Reco', perimetre: 'Scope', moteur_llm: 'Audit engine (LLM)' },
};
const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const CRIT_CLASS = { Fatal: 'fatal', Bloquant: 'bloq', Majeur: 'maj', Standard: 'std' };

// ── M5 v1.5 · ERD : data.db_schema = { bandes:[{key,label}], tables:[{id,bande,label,
//    columns:[{n,t,k(PK|UK|FK),nn,pii,note}]}], relations:[{from,to,enforced,label}] }
function renderERD(db, L = STR.fr) {
  if (!db?.tables?.length) return '';
  const bandes = db.bandes?.length ? db.bandes : [{ key: '_', label: '' }];
  const COLW = 250, GAPX = 60, ROWH = 15, HEADH = 26, GAPY = 26;
  const pos = {}; let maxY = 0;
  bandes.forEach((b, bi) => {
    let y = 34;
    for (const t of db.tables.filter(t => (t.bande ?? '_') === b.key)) {
      const h = HEADH + (t.columns?.length ?? 0) * ROWH + 8;
      pos[t.id] = { x: 20 + bi * (COLW + GAPX), y, w: COLW, h };
      y += h + GAPY;
    }
    maxY = Math.max(maxY, y);
  });
  const W = 20 + bandes.length * (COLW + GAPX), H = maxY + 10;
  const tbl = (t) => {
    const p = pos[t.id];
    return `<g class="erd-t"><rect x="${p.x}" y="${p.y}" width="${p.w}" height="${p.h}" rx="6"/>
      <rect x="${p.x}" y="${p.y}" width="${p.w}" height="${HEADH - 6}" rx="6" class="erd-h"/>
      <text x="${p.x + p.w / 2}" y="${p.y + 14}" text-anchor="middle" class="erd-tt">${esc(t.label ?? t.id)}</text>
      ${(t.columns ?? []).map((c, i) => `<text x="${p.x + 10}" y="${p.y + HEADH + 6 + i * ROWH}" class="erd-c${c.pii ? ' pii' : ''}">${c.k ? `[${esc(c.k)}] ` : ''}${esc(c.n)}${c.nn ? ' *' : ''}${c.pii ? ' 🔒' : ''}</text>
       <text x="${p.x + p.w - 10}" y="${p.y + HEADH + 6 + i * ROWH}" text-anchor="end" class="erd-ty">${esc(c.t ?? '')}</text>`).join('')}</g>`;
  };
  const rel = (r) => {
    const a = pos[String(r.from).split('.')[0]], b = pos[String(r.to).split('.')[0]];
    if (!a || !b) return '';
    const x1 = a.x + a.w, y1 = a.y + 13, x2 = b.x, y2 = b.y + 13;
    const mid = x2 > x1 ? (x1 + x2) / 2 : x1 + 24;
    return `<path d="M ${x1} ${y1} L ${mid} ${y1} L ${mid} ${y2} L ${x2} ${y2}" class="erd-r${r.enforced === false ? ' soft' : ''}" marker-end="url(#erdArr)"><title>${esc(r.from)} → ${esc(r.to)}${r.enforced === false ? ' (référence logique)' : ' (FK)'}</title></path>`;
  };
  const dict = db.tables.map(t => `<tr><td><b>${esc(t.label ?? t.id)}</b></td><td>${(t.columns ?? []).length}</td>
    <td>${(t.columns ?? []).filter(c => c.pii).map(c => `<code>${esc(c.n)}</code>`).join(' ') || '—'}</td>
    <td class="muted">${esc(t.note ?? '')}</td></tr>`).join('');
  return `<h3>${L.erd}</h3>
  <div style="overflow-x:auto"><svg viewBox="0 0 ${W} ${H}" style="min-width:${Math.min(W, 1200)}px" role="img" aria-label="Schéma de base de données">
    <defs><marker id="erdArr" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L10,5 L0,10 z" fill="var(--muted)"/></marker></defs>
    ${bandes.map((b, bi) => b.label ? `<text x="${20 + bi * (COLW + GAPX)}" y="18" class="erd-band">${esc(b.label)}</text>` : '').join('')}
    ${(db.relations ?? []).map(rel).join('')}${db.tables.map(tbl).join('')}
  </svg></div>
  <table><thead><tr><th>${L.table}</th><th>${L.colonnes}</th><th>PII 🔒</th><th>${L.note}</th></tr></thead><tbody>${dict}</tbody></table>
  <p class="muted small">${L.legende_erd}</p>`;
}

// ── M5 v1.5 · Schéma d'architecture : data.architecture = { bandes:[{key,label}],
//    nodes:[{id,bande,label,sub,style}], edges:[{from,to,style,label}] } — auto-layout barycentre.
function renderArchi(arch, L = STR.fr) {
  if (!arch?.nodes?.length) return '';
  const bandes = arch.bandes?.length ? arch.bandes : [{ key: '_', label: '' }];
  const NW = 180, NH = 56, GX = 34, BH = 120, W = 1240;
  const byBande = bandes.map(b => arch.nodes.filter(n => (n.bande ?? '_') === b.key));
  const pos = {};
  byBande.forEach((nodes, bi) => {
    // barycentre : ordonner selon la position moyenne des voisins de la bande précédente
    if (bi > 0) {
      const score = (n) => {
        const nb = (arch.edges ?? []).filter(e => e.to === n.id || e.from === n.id)
          .map(e => pos[e.to === n.id ? e.from : e.to]).filter(Boolean);
        return nb.length ? nb.reduce((s, p) => s + p.x, 0) / nb.length : W / 2;
      };
      nodes.sort((a, b) => score(a) - score(b));
    }
    const total = nodes.length * NW + (nodes.length - 1) * GX;
    let x = Math.max(20, (W - total) / 2);
    for (const n of nodes) { pos[n.id] = { x, y: 40 + bi * BH, w: NW, h: NH }; x += NW + GX; }
  });
  const H = 40 + bandes.length * BH;
  const STYLE = { purple: 'a-purple', blue: 'a-blue', teal: 'a-teal', coral: 'a-coral', amber: 'a-amber', gray: 'a-gray' };
  const node = (n) => {
    const p = pos[n.id];
    return `<g class="${STYLE[n.style] ?? 'a-gray'}"><title>${esc(n.tip ?? n.label)}</title>
      <rect x="${p.x}" y="${p.y}" width="${p.w}" height="${p.h}" rx="8"/>
      <text x="${p.x + p.w / 2}" y="${p.y + 24}" text-anchor="middle" class="a-t">${esc(n.label)}</text>
      <text x="${p.x + p.w / 2}" y="${p.y + 42}" text-anchor="middle" class="a-s">${esc(n.sub ?? '')}</text></g>`;
  };
  const edge = (e) => {
    const a = pos[e.from], b = pos[e.to];
    if (!a || !b) return '';
    const x1 = a.x + a.w / 2, y1 = a.y + a.h, x2 = b.x + b.w / 2, y2 = b.y;
    const d = y2 > y1
      ? (Math.abs(x1 - x2) < 8 ? `M ${x1} ${y1} L ${x2} ${y2}` : `M ${x1} ${y1} L ${x1} ${(y1 + y2) / 2} L ${x2} ${(y1 + y2) / 2} L ${x2} ${y2}`)
      : `M ${a.x + a.w} ${a.y + a.h / 2} L ${b.x} ${b.y + b.h / 2}`;
    return `<path d="${d}" class="a-e${e.style === 'dashed' ? ' dashed' : ''}${e.style === 'coral' ? ' coral' : ''}" marker-end="url(#aArr)">${e.label ? `<title>${esc(e.label)}</title>` : ''}</path>`;
  };
  return `<h3>${L.archi}</h3>
  <div style="overflow-x:auto"><svg viewBox="0 0 ${W} ${H}" style="min-width:900px" role="img" aria-label="Schéma d'architecture">
    <defs><marker id="aArr" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L10,5 L0,10 z" fill="#475569"/></marker></defs>
    ${bandes.map((b, bi) => `<text x="16" y="${34 + bi * BH}" class="erd-band">${esc(b.label)}</text>`).join('')}
    ${(arch.edges ?? []).map(edge).join('')}${arch.nodes.map(node).join('')}
  </svg></div>`;
}

// ─────────────────────────────────────────────────────────────────────────────
// ECR-04/05 — PLAN DE REMÉDIATION consolidé, calculé UNE fois et servi sous trois
// formes : l'onglet lisible, le bloc JSON embarqué (le rapport est auto-porteur —
// le projet n'a aucun export à demander), et le YAML latéral consommé par la forge.
// Une seule source de calcul : les trois formes ne peuvent pas diverger.
//
// Le critère de clôture n'est JAMAIS inventé. Absent des données, il sort en
// placeholder — le rapport est alors incomplet et le gate de rendu le refuse.
// ─────────────────────────────────────────────────────────────────────────────
const PRIO_OF_SEV = { critique: 'urgent', Fatal: 'urgent', majeur: 'prio', Bloquant: 'prio', Majeur: 'prio', mineur: 'norm', Standard: 'norm' };
const SEV_OF_VERDICT = { non_conforme: 'Bloquant', partiel: 'Majeur' };
const CRITERE_ABSENT = '{{CRITERE_DE_CLOTURE}}';

/** Dimension d'une règle : métadonnée bakée par la fusion, sinon déduite de l'identifiant. */
const dimOfRule = (r, index = {}) => {
  const d = (index[r.id]?.dimension_audit ?? r.dimension_audit ?? '').split(' ')[0];
  return /^D(0\d|1[0-6])$/.test(d) ? d : (r.id.match(/\bD(0\d|1[0-6])\b/)?.[0] ?? null);
};

export function buildPlan(data) {
  const index = data._constraints_index ?? {};
  const brut = [];
  // 1 · plan d'action des dimensions
  (data.actions ?? []).forEach((a, i) => {
    brut.push({
      dim: /^D(0\d|1[0-6])$/.test(a.dimension ?? '') ? a.dimension : null,
      id_force: a.id ?? null,
      action: [a.titre, a.desc].filter(Boolean).join(' — '),
      titre: a.titre ?? `Action ${i + 1}`,
      priorite: a.tag ?? 'norm',
      effort: a.effort ?? '—',
      severite: a.severite ?? 'Standard',
      source: a.dimension ?? '—', source_type: 'dimension',
      verification: a.verification ?? CRITERE_ABSENT,
      activation: a.activation ?? null,
    });
  });
  // 2 · règles non conformes ou partielles — jamais écartées silencieusement
  (data.regles ?? []).filter(r => r.verdict === 'non_conforme' || r.verdict === 'partiel').forEach(r => {
    brut.push({
      dim: dimOfRule(r, index),
      id_force: null,
      action: r.possible ?? r.remediation ?? `Mettre en conformité ${r.id}`,
      titre: r.possible ?? r.remediation ?? `Conformité ${r.id}`,
      priorite: PRIO_OF_SEV[r.criticite ?? index[r.id]?.criticite] ?? (r.verdict === 'non_conforme' ? 'prio' : 'norm'),
      effort: r.effort ?? '—',
      severite: r.criticite ?? index[r.id]?.criticite ?? SEV_OF_VERDICT[r.verdict] ?? 'Standard',
      source: r.id, source_type: 'regle',
      verification: r.verification_cloture ?? CRITERE_ABSENT,
      activation: r.activation ?? null,
    });
  });
  // Identifiants stables au format du contrat forge : REM-D<nn>-<nnn>, séquence par dimension.
  // Une action dont la dimension est indéterminable garde un id explicite « non rattaché » :
  // elle reste VISIBLE au plan (jamais écartée), et sort du YAML avec une trace (cf. planToActions).
  const seq = {};
  const plan = brut.map(b => {
    let id = b.id_force;
    if (!id) {
      if (b.dim) { seq[b.dim] = (seq[b.dim] ?? 0) + 1; id = `${b.dim}-${String(seq[b.dim]).padStart(3, '0')}`; id = `REM-${id}`; }
      else id = `REM-NR-${b.source}`;
    }
    const { dim, id_force, ...reste } = b;
    return { id, dimension: dim, ...reste };
  });
  const ordre = { urgent: 0, prio: 1, quick: 2, norm: 3 };
  return plan.sort((a, b) => (ordre[a.priorite] ?? 9) - (ordre[b.priorite] ?? 9));
}

/** Projection du plan vers le contrat `remediation-actions.schema.json` (entrée de la forge). */
export function planToActions(plan, data, coreVersion) {
  const SEV_OK = new Set(['Fatal', 'Bloquant', 'Majeur', 'Standard']);
  const PRIO_OK = new Set(['urgent', 'prio', 'quick', 'norm']);
  // Le contrat forge impose un identifiant rattaché à une dimension. Une action non rattachée
  // n'est pas silencieusement supprimée : elle est exclue du YAML et RENDUE dans `non_projete`,
  // pour que l'écart se voie au lieu de se perdre (garde-fou « pas de troncature muette »).
  const projetables = plan.filter(a => /^REM-D(0\d|1[0-6])-\d{3}$/.test(a.id));
  const nonProjetees = plan.filter(a => !projetables.includes(a));
  const doc = {
    audit_ref: `${data.projet?.nom ?? data.titre ?? 'audit'} — ${data.date ?? ''}${data.indice ?? ''}`.trim(),
    core_version: String(coreVersion || '0.0.0'),
    project: { repo: data.projet?.repo ?? 'non renseigné', stack_profile: data.projet?.stack_profile ?? 'none' },
    actions: projetables.map(a => ({
      id: a.id,
      title: a.titre.slice(0, 120),
      control_ref: a.source_type === 'regle' ? a.source : `dimension:${a.source}`,
      severity: SEV_OK.has(a.severite) ? a.severite : 'Standard',
      priority: PRIO_OK.has(a.priorite) ? a.priorite : 'norm',
      ...(a.effort && a.effort !== '—' ? { effort: a.effort } : {}),
      // Règle d'honnêteté (PLAN/06 §5) : une activation non déclarée n'est JAMAIS
      // présumée automatisable — elle retombe en manuel avec un propriétaire à désigner.
      activation: a.activation ?? {
        mode: 'manual',
        reason: "mode d'activation non déclaré par le rapport d'audit — à qualifier avant bascule forge",
        owner_role: 'à désigner',
      },
      verification: { evidence_expected: a.verification },
      // La forge consomme des stories : toute action activable en forge doit en porter une,
      // dont le critère d'acceptation EST le critère de clôture (jamais deux vérités).
      ...(a.activation && a.activation.mode !== 'manual' ? {
        story: {
          epic: `Dimension ${a.dimension ?? a.source}`,
          title: a.titre.slice(0, 120),
          acceptance: [a.verification],
        },
      } : {}),
    })),
  };
  return { doc, nonProjetees };
}

export function renderRapport(data, { tenant, dimensions, families, themeCss = '', coreVersion = '', lang = 'fr' } = {}) {
  const L = STR[lang] ?? STR.fr;
  const dims = dimensions ?? [];
  const famList = families ?? [...new Set(dims.map(d => d.family))].map(k => ({ key: k, label: k }));
  const byId = Object.fromEntries((data.dimensions ?? []).map(d => [d.id, d]));
  const scored = dims.map(d => ({ ...d, ...byId[d.id] })).filter(d => byId[d.id]);
  const applicable = scored.filter(d => d.applicability !== 'off' && d.score !== undefined);

  const scoreGlobal = applicable.length
    ? (applicable.reduce((s, d) => s + d.score, 0) / applicable.length).toFixed(1) : '—';
  const bloquants = scored.filter(d => d.score <= 2 || d.criticite === 'Fatal' || d.criticality === 'fatal');
  const gate = data.gate?.verdict
    ?? (scored.some(d => d.gate1b === 'nogo') || bloquants.length >= 5 ? 'NO-GO'
      : scored.some(d => d.gate1b === 'reserve') || bloquants.length ? 'GO SOUS RÉSERVE' : 'GO');
  const gateClass = gate === 'GO' ? 'std' : gate === 'NO-GO' ? 'fatal' : 'maj';

  // index des règles (métadonnées bakées depuis la fusion : dimension, criticité, bucket…)
  const meta = data._constraints_index ?? {};
  const regles = (data.regles ?? []).map(r => ({ ...meta[r.id], ...r, id: r.id }));
  const dimOfRegle = (r) => r.dimension_audit?.split(' ')[0] ?? (r.id.match(/CTL-(D\d\d)/)?.[1] ?? '—');

  // ── radar par famille (SVG hexagone)
  const famAvg = famList.map(f => {
    const ds = applicable.filter(d => d.family === f.key);
    return { ...f, avg: ds.length ? ds.reduce((s, d) => s + d.score, 0) / ds.length : 0 };
  });
  const R = 110, CX = 150, CY = 140;
  const pt = (i, v) => {
    const a = -Math.PI / 2 + (2 * Math.PI * i) / famAvg.length;
    return `${(CX + Math.cos(a) * R * (v / 5)).toFixed(1)},${(CY + Math.sin(a) * R * (v / 5)).toFixed(1)}`;
  };
  const radar = `<svg viewBox="0 0 460 290" class="radar" role="img" aria-label="Scores par famille">
    ${[1, 2, 3, 4, 5].map(v => `<polygon points="${famAvg.map((_, i) => pt(i, v)).join(' ')}" fill="none" stroke="var(--line)" stroke-width="${v === 5 ? 1.2 : 0.6}"/>`).join('')}
    <polygon points="${famAvg.map((f, i) => pt(i, f.avg)).join(' ')}" fill="var(--accent)" fill-opacity="0.18" stroke="var(--accent)" stroke-width="2"/>
    ${famAvg.map((f, i) => { const [x, y] = pt(i, 5.65).split(','); return `<text x="${x}" y="${y}" text-anchor="middle" class="rlab">${esc(f.label)} · ${f.avg ? f.avg.toFixed(1) : '—'}</text>`; }).join('')}
  </svg>`;

  // ── section par dimension
  const dimSection = (d) => {
    const info = byId[d.id] ?? {};
    const rs = regles.filter(r => dimOfRegle(r) === d.id);
    const cs = (data.constats ?? []).filter(c => (c.dimension ?? '—') === d.id)
      .sort((a, b) => (SEV[a.severite] ?? 9) - (SEV[b.severite] ?? 9));
    const as_ = (data.actions ?? []).filter(a => (a.dimension ?? '—') === d.id)
      .sort((a, b) => (TAG[a.tag] ?? 9) - (TAG[b.tag] ?? 9));
    return `<section class="dim" id="${d.id}">
      <h3>${d.id} — ${esc(d.label)}
        <span class="badges">${info.score !== undefined ? `<span class="badge">score ${info.score}/5</span>` : `<span class="badge">${L.so}</span>`}
        ${info.criticite ? `<span class="badge b-${CRIT_CLASS[info.criticite] ?? 'std'}">${esc(info.criticite)}</span>` : ''}
        ${info.gate1b ? `<span class="badge b-${info.gate1b === 'go' ? 'std' : info.gate1b === 'nogo' ? 'fatal' : 'maj'}">${esc(info.gate1b)}</span>` : ''}</span></h3>
      ${info.resume ? `<p>${esc(info.resume)}</p>` : ''}
      ${info.preuves?.length ? `<p class="muted">${L.preuves_score} : ${info.preuves.map(p => `<code>${esc(typeof p === 'string' ? p : p.ref ?? p.desc)}</code>`).join(' · ')}</p>` : ''}
      ${rs.length ? `<table><thead><tr><th>${L.regle}</th><th>${L.verdict}</th><th>${L.preuve}</th><th>${L.remede}</th></tr></thead><tbody>
        ${rs.map(r => `<tr><td><code>${esc(r.id)}</code><div class="muted small">${esc((r.regle ?? '').slice(0, 90))}</div></td>
          <td><span class="badge v-${esc(r.verdict)}">${esc(r.verdict ?? '—')}</span></td>
          <td>${esc(r.preuve ?? r.motif ?? '—')}</td><td>${esc(r.possible ?? r.remediation ?? '—')}</td></tr>`).join('')}
      </tbody></table>` : `<p class="muted">${L.sans_regle}</p>`}
      ${cs.length ? `<h4>${L.constats}</h4>${cs.map(c => `<div class="constat s-${esc(c.severite)}"><b>${esc(c.titre)}</b> <span class="badge">${esc(c.severite)}</span><br>${esc(c.desc ?? '')}
        ${(c.preuves ?? []).map(p => `<div class="muted small">↳ ${esc(p.type ?? 'PREUVE')} · <code>${esc(p.ref ?? '')}</code> ${esc(p.desc ?? '')}</div>`).join('')}</div>`).join('')}` : ''}
      ${as_.length ? `<h4>${L.plan}</h4><table><thead><tr><th></th><th>${L.action}</th><th>${L.effort}</th></tr></thead><tbody>
        ${as_.map(a => `<tr><td><span class="badge t-${esc(a.tag)}">${esc(a.tag)}</span></td><td><b>${esc(a.titre)}</b><div class="muted small">${esc(a.desc ?? '')}</div></td><td>${esc(a.effort ?? '—')}</td></tr>`).join('')}
      </tbody></table>` : ''}
    </section>`;
  };

  const famTabs = famList.map((f, i) => {
    const ds = dims.filter(d => d.family === f.key);
    return `<div class="tab-panel" id="fam-${esc(f.key)}" ${i ? 'hidden' : ''}>${ds.map(dimSection).join('')}</div>`;
  }).join('');

  const allRules = `<div class="tab-panel" id="fam-__regles" hidden>
    <input type="search" id="rq" placeholder="${L.filtrer}" oninput="filtreRegles()">
    <table id="rtable"><thead><tr><th>ID</th><th>${L.dim}</th><th>${L.verdict}</th><th>${L.crit}</th><th>Bucket</th><th>Enforcement</th><th>${L.preuve}</th></tr></thead><tbody>
    ${regles.map(r => `<tr><td><code>${esc(r.id)}</code></td><td>${esc(dimOfRegle(r))}</td>
      <td><span class="badge v-${esc(r.verdict)}">${esc(r.verdict ?? '—')}</span></td>
      <td>${esc(r.criticite ?? '—')}</td><td>${esc(r.bucket ?? '—')}</td><td>${esc(r.enforcement ?? '—')}</td>
      <td>${esc(r.preuve ?? r.motif ?? '—')}</td></tr>`).join('')}
    </tbody></table></div>`;

  const reprise = (data.reprise ?? []).length ? `<div class="tab-panel" id="fam-__reprise" hidden><table>
    <thead><tr><th>${L.info}</th><th>${L.valeur}</th><th>${L.statut}</th></tr></thead><tbody>
    ${data.reprise.map(r => `<tr><td>${esc(r.label)}</td><td>${esc(r.value ?? r.valeur ?? '')}</td><td><span class="badge st-${esc(r.status ?? r.statut)}">${esc(r.status ?? r.statut ?? '')}</span></td></tr>`).join('')}
  </tbody></table></div>` : '';

  // ── ECR-05 · plan de remédiation consolidé (onglet lisible)
  const plan = buildPlan(data);
  const planIncomplet = plan.filter(a => /\{\{/.test(`${a.action} ${a.verification}`));
  const remTab = plan.length ? `<div class="tab-panel" id="fam-__remediation" hidden>
    <p class="muted small">${L.rem_intro}${planIncomplet.length ? ` — <b>${planIncomplet.length} ${L.rem_sans_critere}</b>` : ''}</p>
    <table id="remtable"><thead><tr><th>ID</th><th>${L.action}</th><th>${L.prio}</th><th>${L.effort}</th><th>${L.source}</th><th>${L.critere}</th></tr></thead><tbody>
    ${plan.map(a => `<tr><td><code>${esc(a.id)}</code></td><td>${esc(a.action)}</td>
      <td><span class="badge t-${esc(a.priorite)}">${esc(a.priorite)}</span></td><td>${esc(a.effort)}</td>
      <td><code>${esc(a.source)}</code></td><td>${esc(a.verification)}</td></tr>`).join('')}
    </tbody></table></div>` : '';

  // ── ECR-05 · onglets annexes. Sémantique opposable (règle 18) : ANALYSES = outillage
  // EXÉCUTÉ (outil + version utilisée + sortie) ; COMPOSANTS = briques VERSIONNÉES.
  // Une revue humaine n'est ni l'un ni l'autre : elle vit en constat de dimension.
  const annexe = (key, label, cols, rows) => rows?.length ? `<div class="tab-panel" id="fam-${key}" hidden>
    <table id="t-${key}"><thead><tr>${cols.map(c => `<th>${esc(c[1])}</th>`).join('')}</tr></thead><tbody>
    ${rows.map(r => `<tr>${cols.map(c => `<td>${esc(r[c[0]] ?? '—')}</td>`).join('')}</tr>`).join('')}
    </tbody></table></div>` : '';
  const testsTab = annexe('__tests', L.tests,
    [['type', L.type], ['portee', L.portee], ['resultat', L.resultat], ['couverture', L.couverture]], data.tests);
  const analysesTab = annexe('__analyses', L.analyses,
    [['outil', L.outil], ['categorie', L.categorie], ['version_utilisee', L.version_utilisee], ['resultat', L.resultat]], data.analyses);
  const composantsTab = annexe('__composants', L.composants,
    [['nom', L.nom], ['version_resolue', L.version_resolue], ['version_actuelle', L.version_actuelle],
      ['statut', L.statut], ['reco_flag', L.reco], ['perimetre', L.perimetre]], data.composants);

  const erd = renderERD(data.db_schema, L);
  const archi = renderArchi(data.architecture, L);
  const schemaTab = (erd || archi)
    ? `<div class="tab-panel" id="fam-__schemas" hidden>${archi}${archi && erd ? '<hr style="border:none;border-top:1px solid var(--line);margin:24px 0">' : ''}${erd}</div>` : '';

  const tabs = [...famList.map(f => [f.key, f.label]),
    ...(schemaTab ? [['__schemas', L.schemas]] : []),
    ['__regles', `${L.toutes} (${regles.length})`],
    ...(remTab ? [['__remediation', `${L.rem} (${plan.length})`]] : []),
    ...(testsTab ? [['__tests', L.tests]] : []),
    ...(analysesTab ? [['__analyses', L.analyses]] : []),
    ...(composantsTab ? [['__composants', L.composants]] : []),
    ...(reprise ? [['__reprise', L.reprise]] : [])];

  // ── ECR-04/05 · le rapport est AUTO-PORTEUR de sa remédiation : bloc machine embarqué.
  // Le projet n'a aucun export à demander — il lit le HTML qu'on lui a remis.
  const planJson = JSON.stringify({
    schema: 'auditcore.remediation-plan/v1',
    meta: {
      projet: data.projet?.nom ?? data.titre ?? null,
      date: `${data.date ?? ''}${data.indice ?? ''}` || null,
      verdict_gate1b: gate,
      core_version: coreVersion || null,
      // ECR-07 · quel LLM a réalisé l'AUDIT (distinct du LLM éventuel de l'application auditée)
      moteur_audit_llm: data.moteur_audit_llm ?? null,
    },
    actions: plan,
  });
  // Faits nécessaires à l'auto-test interne du rapport (check 9 du gate de rendu).
  const selfTestJson = JSON.stringify({
    gate_declare: gate,
    bloquants: bloquants.map(b => b.id),
    dimensions_nogo: scored.filter(d => d.gate1b === 'nogo').map(d => d.id),
    regles_non_conformes: regles.filter(r => r.verdict === 'non_conforme').map(r => r.id),
    analyses_sans_version: (data.analyses ?? []).filter(a => !String(a.version_utilisee ?? '').trim()).map(a => a.outil ?? '?'),
  });

  return `<!DOCTYPE html><html lang="${esc(lang)}"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(tenant)} — ${L.rapport} — ${esc(data.projet?.nom ?? data.titre ?? '')}</title>
<style>${themeCss}
.wrap{max-width:1280px;margin:0 auto;padding:24px}h1{font-size:26px;margin:6px 0}h3{margin:22px 0 8px}h4{margin:14px 0 6px}
.gate{padding:10px 16px;border-radius:8px;font-weight:700;display:inline-block;color:#fff}
.gate.std{background:var(--std)}.gate.maj{background:var(--maj)}.gate.fatal{background:var(--fatal)}
.kpis{display:flex;gap:14px;margin:14px 0;flex-wrap:wrap}.kpi{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:12px 18px;min-width:150px}
.kpi b{font-size:22px;display:block}.muted{color:var(--muted)}.small{font-size:11.5px}
table{border-collapse:collapse;width:100%;margin:8px 0;background:var(--panel)}th,td{border:1px solid var(--line);padding:6px 9px;font-size:12.5px;text-align:left;vertical-align:top}
th{background:var(--bg)}
.badge{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:1px 9px;font-size:11px;margin-left:4px;background:var(--panel)}
.b-fatal,.v-non_conforme{color:#fff;background:var(--fatal);border-color:var(--fatal)}.b-bloq{color:#fff;background:var(--bloq);border-color:var(--bloq)}
.b-maj,.v-partiel,.t-prio,.st-partial{color:var(--maj);border-color:var(--maj)}.b-std,.v-conforme,.st-ok{color:var(--std);border-color:var(--std)}
.t-urgent{color:#fff;background:var(--fatal);border-color:var(--fatal)}.v-sans_objet,.v-a_evaluer,.st-manual{color:var(--muted)}.st-gap{color:var(--fatal);border-color:var(--fatal)}
.tabs{display:flex;gap:6px;flex-wrap:wrap;border-bottom:2px solid var(--line);margin:18px 0 10px}
.tabs button{border:1px solid var(--line);border-bottom:none;background:var(--panel);padding:8px 14px;border-radius:8px 8px 0 0;cursor:pointer;font:inherit}
.tabs button.on{background:var(--accent);color:#fff;border-color:var(--accent)}
.constat{border-left:3px solid var(--line);padding:6px 10px;margin:6px 0;background:var(--panel)}
.constat.s-critique{border-color:var(--fatal)}.constat.s-majeur{border-color:var(--maj)}
.radar{max-width:460px}.rlab{font-size:10.5px;fill:var(--txt)}
.erd-t rect{fill:var(--panel);stroke:var(--line);stroke-width:1.2}.erd-h{fill:var(--bg)!important}
.erd-tt{font-weight:700;font-size:11.5px;fill:var(--txt)}.erd-c{font-size:10px;fill:var(--txt)}.erd-c.pii{fill:var(--fatal)}
.erd-ty{font-size:9.5px;fill:var(--muted)}.erd-band{font-size:10px;font-weight:700;letter-spacing:.08em;fill:var(--muted);text-transform:uppercase}
.erd-r{fill:none;stroke:var(--muted);stroke-width:1.3}.erd-r.soft{stroke-dasharray:5 3}
.a-t{font-weight:700;font-size:12px}.a-s{font-size:10px}
.a-purple rect{fill:#ede9fe;stroke:#c4b5fd}.a-purple text{fill:#5b21b6}.a-blue rect{fill:#dbeafe;stroke:#93c5fd}.a-blue text{fill:#1d4ed8}
.a-teal rect{fill:#ccfbf1;stroke:#5eead4}.a-teal text{fill:#0f766e}.a-coral rect{fill:#fee2e2;stroke:#fca5a5}.a-coral text{fill:#b91c1c}
.a-amber rect{fill:#fef3c7;stroke:#fcd34d}.a-amber text{fill:#92400e}.a-gray rect{fill:#f1f3f7;stroke:#cbd5e1}.a-gray text{fill:#374151}
.a-e{fill:none;stroke:#475569;stroke-width:1.5}.a-e.dashed{stroke-dasharray:5 3;stroke:#94a3b8}.a-e.coral{stroke:#b91c1c}
input[type=search]{width:100%;padding:8px;border:1px solid var(--line);border-radius:8px;margin:6px 0;font:inherit}
@media print{.tabs{display:none}.tab-panel{display:block!important}}
</style></head><body><div class="wrap">
<header><span class="brand">${esc(data._short_code ?? '')}</span> <b>${esc(tenant)}</b> — ${L.rapport} — <b>${esc(data.projet?.nom ?? data.titre ?? '')}</b>
 <span class="muted">· ${esc(data.date ?? '')}${esc(data.indice ?? '')} · core ${esc(coreVersion)} · ${L.auditeur} : ${esc(data.auditeur ?? '—')}${
  data.moteur_audit_llm ? ` · ${L.moteur_llm} : ${esc([data.moteur_audit_llm.modele, data.moteur_audit_llm.modele_id, data.moteur_audit_llm.date].filter(Boolean).join(' · '))}` : ''
}</span></header>
<h1>${L.gate} : <span class="gate ${gateClass}">${esc(gate)}</span></h1>
<div class="kpis">
 <div class="kpi"><span class="muted">${L.score}</span><b>${scoreGlobal}/5</b><span class="muted small">${applicable.length} ${L.instruites}</span></div>
 <div class="kpi"><span class="muted">${L.bloquants}</span><b>${bloquants.length}</b><span class="muted small">${esc(bloquants.map(b => b.id).join(' · ') || '—')}</span></div>
 <div class="kpi"><span class="muted">${L.regles}</span><b>${regles.length}</b><span class="muted small">${regles.filter(r => r.verdict === 'non_conforme').length} ${L.nc}</span></div>
</div>
${data.syntheses ? `<table><tbody>${Object.entries(data.syntheses).map(([k, v]) => `<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`).join('')}</tbody></table>` : ''}
<h3>${L.familles}</h3>${radar}
<div class="tabs">${tabs.map(([k, l], i) => `<button class="${i ? '' : 'on'}" onclick="tab('${k}',this)">${esc(l)}</button>`).join('')}</div>
${famTabs}${schemaTab}${allRules}${remTab}${testsTab}${analysesTab}${composantsTab}${reprise}
<footer class="muted small" style="margin-top:28px;border-top:1px solid var(--line);padding-top:10px">
${L.footer.replace('{v}', esc(coreVersion)).replace('{t}', esc(tenant))}</footer>
</div>
<script type="application/json" id="remediation-plan-json">${planJson.replace(/</g, '\\u003c')}</script>
<script type="application/json" id="audit-selftest-data">${selfTestJson.replace(/</g, '\\u003c')}</script>
<script>
function tab(k,btn){document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=true);
 var el=document.getElementById('fam-'+k); if(el) el.hidden=false;
 document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('on')); btn.classList.add('on');}
function filtreRegles(){var q=document.getElementById('rq').value.toLowerCase();
 document.querySelectorAll('#rtable tbody tr').forEach(function(tr){tr.style.display=tr.textContent.toLowerCase().includes(q)?'':'none';});}
/* ECR-04 — plan de remédiation auto-porté : accessible sans export, sans navigateur. */
function __auditJson(id){var e=document.getElementById(id); if(!e) return null;
 try{return JSON.parse(e.textContent);}catch(_){return null;}}
function remMeta(){return (__auditJson('remediation-plan-json')||{}).meta||{};}
function buildRemediationPlan(){return (__auditJson('remediation-plan-json')||{}).actions||[];}
var REMEDIATION_PLAN=buildRemediationPlan();
try{window.REMEDIATION_PLAN=REMEDIATION_PLAN;}catch(_){}
/* ECR-02 check 9 — AUTO-TEST INTERNE. Le gate externe hérite de son verdict : tout
   contrôle ajouté ici est couvert automatiquement, sans toucher au vérificateur. */
function auditSelfTest(){
 var e=[], d=__auditJson('audit-selftest-data')||{}, p=buildRemediationPlan();
 var calc=(d.dimensions_nogo||[]).length? 'NO-GO' : ((d.bloquants||[]).length? 'GO SOUS RÉSERVE':'GO');
 if(d.gate_declare && d.gate_declare!==calc && !((d.bloquants||[]).length>=5 && d.gate_declare==='NO-GO'))
  e.push('verdict gate declare ('+d.gate_declare+') incoherent avec les dimensions saisies (calcule: '+calc+')');
 var sansCritere=p.filter(function(a){return /\\{\\{/.test(String(a.action)+' '+String(a.verification));});
 if(sansCritere.length) e.push(sansCritere.length+' action(s) de remediation sans critere de cloture: '+sansCritere.map(function(a){return a.id;}).join(', '));
 (d.regles_non_conformes||[]).forEach(function(id){
  if(!p.some(function(a){return a.source===id;})) e.push('regle non conforme sans action de remediation: '+id);});
 if((d.analyses_sans_version||[]).length)
  e.push('inventaire ANALYSES: '+d.analyses_sans_version.length+' entree(s) sans version utilisee — outillage non execute, ou revue humaine mal rangee (deplacer en constat de dimension)');
 return {ok:e.length===0, errors:e};
}
</script></body></html>`;
}
